"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class X509SVIDRequest(_message.Message):
    """The X509SVIDRequest message conveys parameters for requesting an X.509-SVID.
    There are currently no request parameters.
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___X509SVIDRequest: _TypeAlias = X509SVIDRequest  # noqa: Y015

@_typing.final
class X509SVIDResponse(_message.Message):
    """The X509SVIDResponse message carries X.509-SVIDs and related information,
    including a set of global CRLs and a list of bundles the workload may use
    for federating with foreign trust domains.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class FederatedBundlesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.bytes
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.bytes = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SVIDS_FIELD_NUMBER: _builtins.int
    CRL_FIELD_NUMBER: _builtins.int
    FEDERATED_BUNDLES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def svids(self) -> _containers.RepeatedCompositeFieldContainer[Global___X509SVID]:
        """Required. A list of X509SVID messages, each of which includes a single
        X.509-SVID, its private key, and the bundle for the trust domain.
        """

    @_builtins.property
    def crl(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]:
        """Optional. ASN.1 DER encoded certificate revocation lists."""

    @_builtins.property
    def federated_bundles(self) -> _containers.ScalarMap[_builtins.str, _builtins.bytes]:
        """Optional. CA certificate bundles belonging to foreign trust domains that
        the workload should trust, keyed by the SPIFFE ID of the foreign trust
        domain. Bundles are ASN.1 DER encoded.
        """

    def __init__(
        self,
        *,
        svids: _abc.Iterable[Global___X509SVID] | None = ...,
        crl: _abc.Iterable[_builtins.bytes] | None = ...,
        federated_bundles: _abc.Mapping[_builtins.str, _builtins.bytes] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["crl", b"crl", "federated_bundles", b"federated_bundles", "svids", b"svids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___X509SVIDResponse: _TypeAlias = X509SVIDResponse  # noqa: Y015

@_typing.final
class X509SVID(_message.Message):
    """The X509SVID message carries a single SVID and all associated information,
    including the X.509 bundle for the trust domain.
    """

    DESCRIPTOR: _descriptor.Descriptor

    SPIFFE_ID_FIELD_NUMBER: _builtins.int
    X509_SVID_FIELD_NUMBER: _builtins.int
    X509_SVID_KEY_FIELD_NUMBER: _builtins.int
    BUNDLE_FIELD_NUMBER: _builtins.int
    HINT_FIELD_NUMBER: _builtins.int
    spiffe_id: _builtins.str
    """Required. The SPIFFE ID of the SVID in this entry"""
    x509_svid: _builtins.bytes
    """Required. ASN.1 DER encoded certificate chain. MAY include
    intermediates, the leaf certificate (or SVID itself) MUST come first.
    """
    x509_svid_key: _builtins.bytes
    """Required. ASN.1 DER encoded PKCS#8 private key. MUST be unencrypted."""
    bundle: _builtins.bytes
    """Required. ASN.1 DER encoded X.509 bundle for the trust domain."""
    hint: _builtins.str
    """Optional. An operator-specified string used to provide guidance on how this
    identity should be used by a workload when more than one SVID is returned.
    For example, `internal` and `external` to indicate an SVID for internal or
    external use, respectively.
    """
    def __init__(
        self,
        *,
        spiffe_id: _builtins.str = ...,
        x509_svid: _builtins.bytes = ...,
        x509_svid_key: _builtins.bytes = ...,
        bundle: _builtins.bytes = ...,
        hint: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bundle", b"bundle", "hint", b"hint", "spiffe_id", b"spiffe_id", "x509_svid", b"x509_svid", "x509_svid_key", b"x509_svid_key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___X509SVID: _TypeAlias = X509SVID  # noqa: Y015

@_typing.final
class X509BundlesRequest(_message.Message):
    """The X509BundlesRequest message conveys parameters for requesting X.509
    bundles. There are currently no such parameters.
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___X509BundlesRequest: _TypeAlias = X509BundlesRequest  # noqa: Y015

@_typing.final
class X509BundlesResponse(_message.Message):
    """The X509BundlesResponse message carries a set of global CRLs and a map of
    trust bundles the workload should trust.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class BundlesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.bytes
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.bytes = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    CRL_FIELD_NUMBER: _builtins.int
    BUNDLES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def crl(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]:
        """Optional. ASN.1 DER encoded certificate revocation lists."""

    @_builtins.property
    def bundles(self) -> _containers.ScalarMap[_builtins.str, _builtins.bytes]:
        """Required. CA certificate bundles belonging to trust domains that the
        workload should trust, keyed by the SPIFFE ID of the trust domain.
        Bundles are ASN.1 DER encoded.
        """

    def __init__(
        self,
        *,
        crl: _abc.Iterable[_builtins.bytes] | None = ...,
        bundles: _abc.Mapping[_builtins.str, _builtins.bytes] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bundles", b"bundles", "crl", b"crl"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___X509BundlesResponse: _TypeAlias = X509BundlesResponse  # noqa: Y015

@_typing.final
class JWTSVIDRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AUDIENCE_FIELD_NUMBER: _builtins.int
    SPIFFE_ID_FIELD_NUMBER: _builtins.int
    spiffe_id: _builtins.str
    """Optional. The requested SPIFFE ID for the JWT-SVID. If unset, all
    JWT-SVIDs to which the workload is entitled are requested.
    """
    @_builtins.property
    def audience(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Required. The audience(s) the workload intends to authenticate against."""

    def __init__(
        self,
        *,
        audience: _abc.Iterable[_builtins.str] | None = ...,
        spiffe_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audience", b"audience", "spiffe_id", b"spiffe_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___JWTSVIDRequest: _TypeAlias = JWTSVIDRequest  # noqa: Y015

@_typing.final
class JWTSVIDResponse(_message.Message):
    """The JWTSVIDResponse message conveys JWT-SVIDs."""

    DESCRIPTOR: _descriptor.Descriptor

    SVIDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def svids(self) -> _containers.RepeatedCompositeFieldContainer[Global___JWTSVID]:
        """Required. The list of returned JWT-SVIDs."""

    def __init__(
        self,
        *,
        svids: _abc.Iterable[Global___JWTSVID] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["svids", b"svids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___JWTSVIDResponse: _TypeAlias = JWTSVIDResponse  # noqa: Y015

@_typing.final
class JWTSVID(_message.Message):
    """The JWTSVID message carries the JWT-SVID token and associated metadata."""

    DESCRIPTOR: _descriptor.Descriptor

    SPIFFE_ID_FIELD_NUMBER: _builtins.int
    SVID_FIELD_NUMBER: _builtins.int
    HINT_FIELD_NUMBER: _builtins.int
    spiffe_id: _builtins.str
    """Required. The SPIFFE ID of the JWT-SVID."""
    svid: _builtins.str
    """Required. Encoded JWT using JWS Compact Serialization."""
    hint: _builtins.str
    """Optional. An operator-specified string used to provide guidance on how this
    identity should be used by a workload when more than one SVID is returned.
    For example, `internal` and `external` to indicate an SVID for internal or
    external use, respectively.
    """
    def __init__(
        self,
        *,
        spiffe_id: _builtins.str = ...,
        svid: _builtins.str = ...,
        hint: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hint", b"hint", "spiffe_id", b"spiffe_id", "svid", b"svid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___JWTSVID: _TypeAlias = JWTSVID  # noqa: Y015

@_typing.final
class JWTBundlesRequest(_message.Message):
    """The JWTBundlesRequest message conveys parameters for requesting JWT bundles.
    There are currently no such parameters.
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___JWTBundlesRequest: _TypeAlias = JWTBundlesRequest  # noqa: Y015

@_typing.final
class JWTBundlesResponse(_message.Message):
    """The JWTBundlesReponse conveys JWT bundles."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class BundlesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.bytes
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.bytes = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    BUNDLES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def bundles(self) -> _containers.ScalarMap[_builtins.str, _builtins.bytes]:
        """Required. JWK encoded JWT bundles, keyed by the SPIFFE ID of the trust
        domain.
        """

    def __init__(
        self,
        *,
        bundles: _abc.Mapping[_builtins.str, _builtins.bytes] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bundles", b"bundles"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___JWTBundlesResponse: _TypeAlias = JWTBundlesResponse  # noqa: Y015

@_typing.final
class ValidateJWTSVIDRequest(_message.Message):
    """The ValidateJWTSVIDRequest message conveys request parameters for
    JWT-SVID validation.
    """

    DESCRIPTOR: _descriptor.Descriptor

    AUDIENCE_FIELD_NUMBER: _builtins.int
    SVID_FIELD_NUMBER: _builtins.int
    audience: _builtins.str
    """Required. The audience of the validating party. The JWT-SVID must
    contain an audience claim which contains this value in order to
    succesfully validate.
    """
    svid: _builtins.str
    """Required. The JWT-SVID to validate, encoded using JWS Compact
    Serialization.
    """
    def __init__(
        self,
        *,
        audience: _builtins.str = ...,
        svid: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audience", b"audience", "svid", b"svid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ValidateJWTSVIDRequest: _TypeAlias = ValidateJWTSVIDRequest  # noqa: Y015

@_typing.final
class ValidateJWTSVIDResponse(_message.Message):
    """The ValidateJWTSVIDReponse message conveys the JWT-SVID validation results."""

    DESCRIPTOR: _descriptor.Descriptor

    SPIFFE_ID_FIELD_NUMBER: _builtins.int
    CLAIMS_FIELD_NUMBER: _builtins.int
    spiffe_id: _builtins.str
    """Required. The SPIFFE ID of the validated JWT-SVID."""
    @_builtins.property
    def claims(self) -> _struct_pb2.Struct:
        """Optional. Arbitrary claims contained within the payload of the validated
        JWT-SVID.
        """

    def __init__(
        self,
        *,
        spiffe_id: _builtins.str = ...,
        claims: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["claims", b"claims"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["claims", b"claims", "spiffe_id", b"spiffe_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ValidateJWTSVIDResponse: _TypeAlias = ValidateJWTSVIDResponse  # noqa: Y015
