name: Publish to PyPI

on:
  push:
    tags:
      - 'spiffe-*'
      - 'spiffe-tls-*'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install 3.10

      # Conditional step for spiffe module
      - name: Publish spiffe
        if: startsWith(github.ref, 'refs/tags/spiffe-') && !startsWith(github.ref, 'refs/tags/spiffe-tls-')
        run: |
          uv build --package spiffe
          uv publish dist/spiffe-*

      # Conditional step for spiffe-tls module
      - name: Publish spiffe-tls
        if: startsWith(github.ref, 'refs/tags/spiffe-tls-')
        run: |
          uv build --package spiffe-tls
          uv publish dist/spiffe_tls-*
