# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from spiffe.proto import workload_pb2 as spiffe_dot_proto_dot_workload__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in spiffe/proto/workload_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpiffeWorkloadAPIStub(object):
    """///////////////////////////////////////////////////////////////////////
    X509-SVID Profile
    ///////////////////////////////////////////////////////////////////////
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchX509SVID = channel.unary_stream(
                '/SpiffeWorkloadAPI/FetchX509SVID',
                request_serializer=spiffe_dot_proto_dot_workload__pb2.X509SVIDRequest.SerializeToString,
                response_deserializer=spiffe_dot_proto_dot_workload__pb2.X509SVIDResponse.FromString,
                _registered_method=True)
        self.FetchX509Bundles = channel.unary_stream(
                '/SpiffeWorkloadAPI/FetchX509Bundles',
                request_serializer=spiffe_dot_proto_dot_workload__pb2.X509BundlesRequest.SerializeToString,
                response_deserializer=spiffe_dot_proto_dot_workload__pb2.X509BundlesResponse.FromString,
                _registered_method=True)
        self.FetchJWTSVID = channel.unary_unary(
                '/SpiffeWorkloadAPI/FetchJWTSVID',
                request_serializer=spiffe_dot_proto_dot_workload__pb2.JWTSVIDRequest.SerializeToString,
                response_deserializer=spiffe_dot_proto_dot_workload__pb2.JWTSVIDResponse.FromString,
                _registered_method=True)
        self.FetchJWTBundles = channel.unary_stream(
                '/SpiffeWorkloadAPI/FetchJWTBundles',
                request_serializer=spiffe_dot_proto_dot_workload__pb2.JWTBundlesRequest.SerializeToString,
                response_deserializer=spiffe_dot_proto_dot_workload__pb2.JWTBundlesResponse.FromString,
                _registered_method=True)
        self.ValidateJWTSVID = channel.unary_unary(
                '/SpiffeWorkloadAPI/ValidateJWTSVID',
                request_serializer=spiffe_dot_proto_dot_workload__pb2.ValidateJWTSVIDRequest.SerializeToString,
                response_deserializer=spiffe_dot_proto_dot_workload__pb2.ValidateJWTSVIDResponse.FromString,
                _registered_method=True)


class SpiffeWorkloadAPIServicer(object):
    """///////////////////////////////////////////////////////////////////////
    X509-SVID Profile
    ///////////////////////////////////////////////////////////////////////
    """

    def FetchX509SVID(self, request, context):
        """Fetch X.509-SVIDs for all SPIFFE identities the workload is entitled to,
        as well as related information like trust bundles and CRLs. As this
        information changes, subsequent messages will be streamed from the
        server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchX509Bundles(self, request, context):
        """Fetch trust bundles and CRLs. Useful for clients that only need to
        validate SVIDs without obtaining an SVID for themself. As this
        information changes, subsequent messages will be streamed from the
        server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchJWTSVID(self, request, context):
        """///////////////////////////////////////////////////////////////////////
        JWT-SVID Profile
        ///////////////////////////////////////////////////////////////////////

        Fetch JWT-SVIDs for all SPIFFE identities the workload is entitled to,
        for the requested audience. If an optional SPIFFE ID is requested, only
        the JWT-SVID for that SPIFFE ID is returned.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchJWTBundles(self, request, context):
        """Fetches the JWT bundles, formatted as JWKS documents, keyed by the
        SPIFFE ID of the trust domain. As this information changes, subsequent
        messages will be streamed from the server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateJWTSVID(self, request, context):
        """Validates a JWT-SVID against the requested audience. Returns the SPIFFE
        ID of the JWT-SVID and JWT claims.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpiffeWorkloadAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchX509SVID': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchX509SVID,
                    request_deserializer=spiffe_dot_proto_dot_workload__pb2.X509SVIDRequest.FromString,
                    response_serializer=spiffe_dot_proto_dot_workload__pb2.X509SVIDResponse.SerializeToString,
            ),
            'FetchX509Bundles': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchX509Bundles,
                    request_deserializer=spiffe_dot_proto_dot_workload__pb2.X509BundlesRequest.FromString,
                    response_serializer=spiffe_dot_proto_dot_workload__pb2.X509BundlesResponse.SerializeToString,
            ),
            'FetchJWTSVID': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchJWTSVID,
                    request_deserializer=spiffe_dot_proto_dot_workload__pb2.JWTSVIDRequest.FromString,
                    response_serializer=spiffe_dot_proto_dot_workload__pb2.JWTSVIDResponse.SerializeToString,
            ),
            'FetchJWTBundles': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchJWTBundles,
                    request_deserializer=spiffe_dot_proto_dot_workload__pb2.JWTBundlesRequest.FromString,
                    response_serializer=spiffe_dot_proto_dot_workload__pb2.JWTBundlesResponse.SerializeToString,
            ),
            'ValidateJWTSVID': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateJWTSVID,
                    request_deserializer=spiffe_dot_proto_dot_workload__pb2.ValidateJWTSVIDRequest.FromString,
                    response_serializer=spiffe_dot_proto_dot_workload__pb2.ValidateJWTSVIDResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SpiffeWorkloadAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SpiffeWorkloadAPI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpiffeWorkloadAPI(object):
    """///////////////////////////////////////////////////////////////////////
    X509-SVID Profile
    ///////////////////////////////////////////////////////////////////////
    """

    @staticmethod
    def FetchX509SVID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/SpiffeWorkloadAPI/FetchX509SVID',
            spiffe_dot_proto_dot_workload__pb2.X509SVIDRequest.SerializeToString,
            spiffe_dot_proto_dot_workload__pb2.X509SVIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchX509Bundles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/SpiffeWorkloadAPI/FetchX509Bundles',
            spiffe_dot_proto_dot_workload__pb2.X509BundlesRequest.SerializeToString,
            spiffe_dot_proto_dot_workload__pb2.X509BundlesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchJWTSVID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SpiffeWorkloadAPI/FetchJWTSVID',
            spiffe_dot_proto_dot_workload__pb2.JWTSVIDRequest.SerializeToString,
            spiffe_dot_proto_dot_workload__pb2.JWTSVIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchJWTBundles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/SpiffeWorkloadAPI/FetchJWTBundles',
            spiffe_dot_proto_dot_workload__pb2.JWTBundlesRequest.SerializeToString,
            spiffe_dot_proto_dot_workload__pb2.JWTBundlesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateJWTSVID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SpiffeWorkloadAPI/ValidateJWTSVID',
            spiffe_dot_proto_dot_workload__pb2.ValidateJWTSVIDRequest.SerializeToString,
            spiffe_dot_proto_dot_workload__pb2.ValidateJWTSVIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
